version: '3.8'

services:
  investment-simulator:
    build: .
    ports:
      - "8000:8000"
    environment:
      - PYTHONPATH=/app
    volumes:
      - ./logs:/app/logs
    restart: unless-stopped

  # Optional: Add MLflow tracking server
  mlflow:
    image: python:3.10-slim
    ports:
      - "5000:5000"
    command: >
      bash -c "pip install mlflow &&
               mlflow server --host 0.0.0.0 --port 5000 --default-artifact-root ./mlruns"
    volumes:
      - ./mlruns:/mlruns
    restart: unless-stopped
